name: Running Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.17"
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: "2.14.4"
    - run: |
        dart pub get
    - run: |
        go test -v ./...
